package com.cursojava.proyecto.utils.herencia;

public class Normal extends Moves{

    public Normal(){
        super();
        mov.add("Acupresión");
        mov.add("Adaptación");
        mov.add("Afilar");
        mov.add("Agarre");
        mov.add("Agarrón");
        mov.add("Aguante");
        mov.add("Aguzar");
        mov.add("Alboroto");
        mov.add("Alivio");
        mov.add("Amago");
        mov.add("Amortiguador");
        mov.add("Antojo");
        mov.add("Anulación");
        mov.add("Arañazo");
        mov.add("Ariete");
        mov.add("Arrojo intempestivo");
        mov.add("As oculto");
        mov.add("Atadura");
        mov.add("Ataque furia");
        mov.add("Ataque rápido");
        mov.add("Atiborramiento");
        mov.add("Atizar");
        mov.add("Atracción");
        mov.add("Aullido");
        mov.add("Autodestrucción");
        mov.add("Avivar");
        mov.add("Ayuda");
        mov.add("Azote");
        mov.add("Batido");
        mov.add("Beso amoroso");
        mov.add("Bloqueo");
        mov.add("Bomba huevo");
        mov.add("Bomba sónica");
        mov.add("Bostezo");
        mov.add("Cabezazo");
        mov.add("Cambio de cancha");
        mov.add("Camaradería");
        mov.add("Campana cura");
        mov.add("Camuflaje");
        mov.add("Canon");
        mov.add("Canto");
        mov.add("Canto arcaico");
        mov.add("Canto mortal");
        mov.add("Cara susto");
        mov.add("Carrera arrolladora");
        mov.add("Cede paso");
        mov.add("Celebración");
        mov.add("Chirrido");
        mov.add("Clavo cañón");
        mov.add("Clemencia");
        mov.add("Clonatipo");
        mov.add("Confidencia");
        mov.add("Conjuro");
        mov.add("Contoneo");
        mov.add("Conversión");
        mov.add("Conversión2");
        mov.add("Copión");
        mov.add("Cornada");
        mov.add("Corte");
        mov.add("Cosquillas");
        mov.add("Cuchillada");
        mov.add("Danza amiga");
        mov.add("Danza caos");
        mov.add("Danza despertar");
        mov.add("Danza espada");
        mov.add("Daño secreto");
        mov.add("Derribo");
        mov.add("Desarrollo");
        mov.add("Deseo");
        mov.add("Deslumbrar");
        mov.add("Destello");
        mov.add("Destructor");
        mov.add("Día de pago");
        mov.add("Divide dolor");
        mov.add("Doble equipo");
        mov.add("Doble filo");
        mov.add("Doble golpe");
        mov.add("Doble bofetón");
        mov.add("Don natural");
        mov.add("Dulce aroma");
        mov.add("Eco voz");
        mov.add("Escupir");
        mov.add("Esfuerzo");
        mov.add("Esquema");
        mov.add("Estímulo");
        mov.add("Estruendo");
        mov.add("Estrujón");
        mov.add("Explosión");
        mov.add("Falsotortazo");
        mov.add("Fijar blanco");
        mov.add("Foco");
        mov.add("Foco energía");
        mov.add("Fortaleza");
        mov.add("Frustración");
        mov.add("Fuerza");
        mov.add("Furia");
        mov.add("Garra brutal");
        mov.add("Giga impacto");
        mov.add("Giro rápido");
        mov.add("Golpe");
        mov.add("Golpe cabeza");
        mov.add("Golpe cuerpo");
        mov.add("Golpes furia");
        mov.add("Gruñido");
        mov.add("Guardia baja");
        mov.add("Guillotina");
        mov.add("Hiper colmillo");
        mov.add("Hiperrayo");
        mov.add("Hora del té");
        mov.add("Imagen");
        mov.add("Látigo");
        mov.add("Mal de ojo");
        mov.add("Malicioso");
        mov.add("Manos juntas");
        mov.add("Más psique");
        mov.add("Megapatada");
        mov.add("Megapuño");
        mov.add("Meteorobola");
        mov.add("Metrónomo");
        mov.add("Mimético");
        mov.add("Multiataque");
        mov.add("Novena potencia");
        mov.add("Ofrenda");
        mov.add("Ojos llorosos");
        mov.add("Onda simple");
        mov.add("Otra vez");
        mov.add("Paga extra");
        mov.add("Pantalla de humo");
        mov.add("Perforador");
        mov.add("Pisotón");
        mov.add("Placaje");
        mov.add("Plumerazo");
        mov.add("Poder oculto");
        mov.add("Presa");
        mov.add("Presente");
        mov.add("Profecía");
        mov.add("Protección");
        mov.add("Puño cometa");
        mov.add("Puño mareo");
        mov.add("Rapidez");
        mov.add("Rastreo");
        mov.add("Reciclaje");
        mov.add("Recuperación");
        mov.add("Reducción");
        mov.add("Refuerzo");
        mov.add("Relajo");
        mov.add("Relevo");
        mov.add("Remolino");
        mov.add("Constricción");
        mov.add("Represalia");
        mov.add("Reserva");
        mov.add("Restricción");
        mov.add("Retribución");
        mov.add("Rizo defensa");
        mov.add("Rompecoraza");
        mov.add("Ronquido");
        mov.add("Rugido");
        mov.add("Rugido de guerra");
        mov.add("Salpicadura");
        mov.add("Seducción");
        mov.add("Sentencia");
        mov.add("Señuelo");
        mov.add("Sol matinal");
        mov.add("Sonámbulo");
        mov.add("Sorpresa");
        mov.add("Superdiente");
        mov.add("Supersónico");
        mov.add("Sustituto");
        mov.add("Tambor");
        mov.add("Tecno shock");
        mov.add("Telépata");
        mov.add("Tragar");
        mov.add("Transformación");
        mov.add("Treparrocas");
        mov.add("Triataque");
        mov.add("Última baza");
        mov.add("Velo sagrado");
        mov.add("Velocidad extrema");
        mov.add("Venganza");
        mov.add("Viento cortante");
        mov.add("Vozarrón");
        mov.add("Yo primero");
    }
}
